"""add is_active to users

Revision ID: 15136db232a1
Revises: f114b358ba06
Create Date: 2026-08-22 18:26:38.847939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15136db232a1'
down_revision: Union[str, None] = 'f114b358ba06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default=sa.true() added by hand — autogenerate's plain
    # `nullable=False` with no default would fail outright against any
    # row that already exists (Postgres requires ADD COLUMN ... NOT
    # NULL to have a default when the table isn't empty). Kept as a
    # permanent server-side default, not just a backfill-then-drop, so
    # a future INSERT that somehow bypasses the ORM's own
    # `default=True` still gets an active user rather than a NOT NULL
    # violation.
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
