"""create decision_logs table

Revision ID: 40bcf24cb79c
Revises: 6e8373f2fb49
Create Date: 2026-08-22 16:46:43.803004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40bcf24cb79c'
down_revision: Union[str, None] = '6e8373f2fb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_modality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('drift_breakdown', sa.JSON(), nullable=False),
    sa.Column('ifsr_result', sa.JSON(), nullable=False),
    sa.Column('policy_action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matched_rule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pii_found', sa.JSON(), nullable=False),
    sa.Column('latency_ms_per_stage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_created_at'), 'decision_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_logs_policy_action'), 'decision_logs', ['policy_action'], unique=False)
    op.create_index(op.f('ix_decision_logs_session_id'), 'decision_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_session_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_policy_action'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_created_at'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
