"""add user_id and user_email to decision_logs

Attributes every decision log to the user who ran it, so the log/audit
view can be scoped per-user (a viewer/analyst sees only their own runs;
an admin sees all and can filter by user). Both columns are nullable:
decision_logs rows written before this migration have no known owner,
and run_pipeline() can be called with no user at all (tests, eval
scripts, the input-only route).

Hand-written rather than autogenerated — Alembic's autogenerate against
a SQLModel model omits nothing structural here, but keeping the FK and
index explicit (and documented) matters for an audit table.

Revision ID: a1c2e3d4f5b6
Revises: 15136db232a1
Create Date: 2026-08-27
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1c2e3d4f5b6"
down_revision: str | None = "15136db232a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("decision_logs", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("decision_logs", sa.Column("user_email", sa.String(), nullable=True))
    op.create_index(op.f("ix_decision_logs_user_id"), "decision_logs", ["user_id"], unique=False)
    op.create_foreign_key(
        "fk_decision_logs_user_id_users",
        "decision_logs",
        "users",
        ["user_id"],
        ["id"],
        # A deleted user's audit trail must not vanish or block the
        # delete — the log keeps user_id pointing at a now-gone row, and
        # user_email preserves the human-readable identity regardless.
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint("fk_decision_logs_user_id_users", "decision_logs", type_="foreignkey")
    op.drop_index(op.f("ix_decision_logs_user_id"), table_name="decision_logs")
    op.drop_column("decision_logs", "user_email")
    op.drop_column("decision_logs", "user_id")
